CREATE TABLE `ps_v2_runtime_hpa`
(
    `id`                  bigint(20) unsigned NOT NULL AUTO_INCREMENT,
    `created_at`          datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `updated_at`          datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `rule_id`             varchar(36)  NOT NULL COMMENT '规则 ID',
    `rule_name`           varchar(255) NOT NULL COMMENT '规则名称',
    `rule_namespace`      varchar(255) NOT NULL COMMENT '规则部署所在的命名空间',
    `org_id`              bigint(20) unsigned NOT NULL COMMENT '组织ID',
    `org_name`            varchar(64) NOT NULL DEFAULT '' COMMENT '组织名称',
    `org_display_name`    varchar(64) NOT NULL DEFAULT '' COMMENT '组织显示名称',
    `project_id`          bigint(20) unsigned NOT NULL COMMENT '项目ID',
    `project_name`        varchar(64) NOT NULL DEFAULT '' COMMENT '项目名称',
    `proj_display_name`   varchar(64) NOT NULL DEFAULT '' COMMENT '项目显示名称',
    `application_id`      bigint(20) unsigned NOT NULL COMMENT '应用ID',
    `application_name`    varchar(64) NOT NULL DEFAULT '' COMMENT '应用名称',
    `app_display_name`    varchar(64) NOT NULL DEFAULT '' COMMENT '应用显示名称',
    `runtime_id`          bigint(20) unsigned NOT NULL COMMENT 'Runtime ID',
    `runtime_name`        varchar(255) NOT NULL DEFAULT '' COMMENT 'Runtime 名称',
    `workspace`           varchar(16) NOT NULL DEFAULT '' COMMENT '部署环境',
    `cluster_name`        varchar(255) NOT NULL DEFAULT '' COMMENT '集群名称',
    `user_id`             varchar(255) NOT NULL COMMENT '用户Id',
    `user_name`           varchar(255) DEFAULT NULL COMMENT '用户名 (唯一)',
    `nick_name`           varchar(128) DEFAULT NULL COMMENT '用户昵称',
    `service_name`        varchar(255) DEFAULT NULL COMMENT 'HPA 规则关联的服务名称',
    `rules`               text COMMENT 'scaledObject json 缓存',
    `is_applied`          varchar(1)   NOT NULL DEFAULT 'N' COMMENT '规则是否已使用',
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='Runtime HPA信息';